### ISSUE TITLE
Basic Usage and Documentation

### ISSUE THREAD

**Issue by kiarafrobles** [TransparencyToolkit/wordcloud#1]
Can we get some basic usage documentation?
How do I call the WordCloud class on a document or set of documents?

**Comment by kiaraRobles** [comment]
Error I'm getting:
`/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in require: cannot load such file -- wordcloud (LoadError)`

From running this command:
`$ ruby -Ilib -rwordcloud -e "WordCloud.new(osx-config.json, json)"`

**Comment by Shidash** [comment]
This code is deprecated and not maintained, and there will be a better setup for this later. That said, if you want to use it still, you should install the wordcloud gem and then run it as follows-

For a single doc:
w = WordCloud.new("document text", "single")
puts w.parse

For multiple documents:
w = WordCloud.new(["document 1 text", "document 2 text"], "multiple")
puts w.parse
